<script lang="ts">
	import { onMount, getContext } from 'svelte';
	import { goto } from '$app/navigation';
	import { toast } from 'svelte-sonner';

	import { copyToClipboard } from '$lib/utils';
	import BarChart from '$lib/components/billing/BarChart.svelte';
	import {
		getApiKeyPlans,
		createMyTopupRequest,
		getMyApiKeyConsole,
		getMyInvoiceById,
		getMyInvoices,
		getMyTopups,
		getMyUsageSummary,
		getPublicPaymentAccounts,
		regenerateMyApiKey,
		getMyUsageDaily,
		getMyUsageByModel,
		type ApiKeyConsole,
		type ApiKeyPlan,
		type BillingInvoice,
		type PaymentAccount,
		type TopupRequest,
		type UserUsageSummary,
		type UsageDailySummary,
		type UsageByModelSummary
	} from '$lib/apis/api-keys';

	const i18n = getContext<any>('i18n');

	let loading = true;
	let apiKey: ApiKeyConsole | null = null;
	let copied = false;
	let showFullKey = false; // true right after regeneration — one-time display
	let paymentAccounts: PaymentAccount[] = [];
	let topups: TopupRequest[] = [];
	let invoices: BillingInvoice[] = [];
	let plans: ApiKeyPlan[] = [];
	let usage: UserUsageSummary | null = null;
	let selectedPlanId = 'starter';

	let selectedPaymentAccountId = '';
	let topupAmount = 10;
	let topupCurrency = 'USD';
	let topupTxRef = '';
	let topupNote = '';

	let myUsageDaily: UsageDailySummary[] = [];
	let myUsageByModel: UsageByModelSummary[] = [];

	const loadConsole = async () => {
		apiKey = await getMyApiKeyConsole(localStorage.token).catch((error) => {
			toast.error(`${error}`);
			return null;
		});

		paymentAccounts = await getPublicPaymentAccounts(localStorage.token).catch(() => []);
		topups = await getMyTopups(localStorage.token).catch(() => []);
		invoices = await getMyInvoices(localStorage.token).catch(() => []);
		plans = await getApiKeyPlans(localStorage.token).catch(() => []);
		usage = await getMyUsageSummary(localStorage.token).catch(() => null);
		myUsageDaily = await getMyUsageDaily(localStorage.token).catch(() => []);
		myUsageByModel = await getMyUsageByModel(localStorage.token).catch(() => []);

		if (!selectedPaymentAccountId && paymentAccounts.length > 0) {
			selectedPaymentAccountId = paymentAccounts[0].id;
		}

		if (apiKey?.plan_name) {
			selectedPlanId = apiKey.plan_name;
		}
	};

	const selectPlan = (plan: ApiKeyPlan) => {
		selectedPlanId = plan.id;
		topupAmount = plan.monthly_price_usd;
		topupNote = `Subscribe plan ${plan.name}`;
	};

	onMount(async () => {
		await loadConsole();
		loading = false;
	});

	const regenerate = async () => {
		apiKey = await regenerateMyApiKey(localStorage.token).catch((error) => {
			toast.error(`${error}`);
			return apiKey;
		});

		showFullKey = true;
		toast.success($i18n.t('API key regenerated. Copy it now — it will not be shown again.'));
	};

	const submitTopup = async () => {
		if (!apiKey) {
			toast.error($i18n.t('No API key found'));
			return;
		}

		if (!selectedPaymentAccountId) {
			toast.error($i18n.t('Please select a payment account'));
			return;
		}

		await createMyTopupRequest(localStorage.token, {
			api_key_id: apiKey.id,
			payment_account_id: selectedPaymentAccountId,
			amount: Number(topupAmount),
			currency: topupCurrency,
			tx_ref: topupTxRef,
			note: topupNote
		})
			.then(async () => {
				toast.success($i18n.t('Top-up request created'));
				topupTxRef = '';
				topupNote = '';
				await loadConsole();
			})
			.catch((error) => toast.error(`${error}`));
	};

	const exportInvoicePdf = async (invoiceId: string) => {
		const invoice = await getMyInvoiceById(localStorage.token, invoiceId).catch((error) => {
			toast.error(`${error}`);
			return null;
		});

		if (!invoice) return;

		const { default: jsPDF } = await import('jspdf');
		const pdf = new jsPDF('p', 'mm', 'a4');

		let y = 18;
		pdf.setFontSize(16);
		pdf.text('OpenWebUI API Invoice', 14, y);
		y += 10;

		pdf.setFontSize(11);
		const lines = [
			`Invoice ID: ${invoice.id}`,
			`Date: ${new Date(invoice.created_at * 1000).toISOString()}`,
			`User ID: ${invoice.user_id}`,
			`API Key ID: ${invoice.api_key_id}`,
			`Amount: ${invoice.amount} ${invoice.currency}`,
			`Credits: ${invoice.credits}`,
			`Status: ${invoice.status}`,
			`Topup Request ID: ${invoice.topup_request_id ?? '-'}`
		];

		for (const line of lines) {
			pdf.text(line, 14, y);
			y += 7;
		}

		pdf.setFontSize(9);
		y += 4;
		pdf.text('Generated by OpenWebUI Billing Console', 14, y);

		pdf.save(`invoice-${invoice.id}.pdf`);
	};
</script>

<div class="max-w-3xl mx-auto px-4 py-5 space-y-4">
	<div>
		<div class="text-lg font-semibold">{$i18n.t('Developer API Console')}</div>
		<div class="text-xs text-gray-500 flex items-center gap-2">
			{$i18n.t('View your plan, credits and usage for API key access.')}
			<button class="text-xs underline" on:click={() => goto('/developer/api-keys/pricing')}>Pricing</button>
			<button class="text-xs underline" on:click={() => goto('/developer/api-keys/guide')}>Guide</button>
		</div>
	</div>

	{#if loading}
		<div class="text-sm text-gray-500">{$i18n.t('Loading...')}</div>
	{:else if !apiKey}
		<div class="text-sm text-gray-500">{$i18n.t('No API key found. Generate one in account settings first.')}</div>
	{:else}
		<div class="rounded-xl border border-gray-100 dark:border-gray-800 p-4 space-y-3">
			<div class="text-sm font-medium">Plans & Pricing</div>
			<div class="grid grid-cols-1 md:grid-cols-3 gap-2">
				{#each plans as plan}
					<button
						class="rounded-lg border text-left p-3 {selectedPlanId === plan.id
							? 'border-black dark:border-white'
							: 'border-gray-100 dark:border-gray-800'}"
						on:click={() => selectPlan(plan)}
					>
						<div class="font-medium text-sm">{plan.name}</div>
						<div class="text-xs text-gray-500 mt-1">${plan.monthly_price_usd}/month • {plan.included_credits} credits</div>
						<div class="text-xs text-gray-500 mt-1">RPM {plan.rpm_limit} • {plan.support_tier} support</div>
					</button>
				{/each}
			</div>
		</div>

		<div class="rounded-xl border border-gray-100 dark:border-gray-800 p-4 space-y-3">
			<div class="flex items-center justify-between gap-2">
				<div class="font-medium">{$i18n.t('Secret key')}</div>
				<div class="text-xs text-gray-500">{apiKey.key_masked}</div>
			</div>

			{#if showFullKey}
				<div class="rounded-lg bg-amber-50 dark:bg-amber-900/30 border border-amber-200 dark:border-amber-800 p-3 text-xs text-amber-800 dark:text-amber-200">
					<strong>Important:</strong> Copy your API key now. For security, you will not be able to see the full key again after leaving this page.
				</div>
			{/if}

			<div class="flex gap-2">
				<input
					class="w-full rounded-lg px-3 py-2 text-xs bg-transparent border border-gray-200 dark:border-gray-700"
					value={apiKey.key}
					readonly
				/>
				<button
					class="px-3 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 text-xs"
					on:click={() => {
						copyToClipboard(apiKey!.key);
						copied = true;
						setTimeout(() => (copied = false), 1200);
					}}
				>
					{copied ? 'Copied' : 'Copy'}
				</button>
				<button
					class="px-3 py-2 rounded-lg bg-black text-white dark:bg-white dark:text-black text-xs"
					on:click={regenerate}
				>
					Regenerate
				</button>
			</div>

			<div class="grid grid-cols-1 sm:grid-cols-3 gap-3 text-sm">
				<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3">
					<div class="text-xs text-gray-500">Plan</div>
					<div class="font-semibold mt-1">{apiKey.plan_name ?? 'starter'}</div>
				</div>
				<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3">
					<div class="text-xs text-gray-500">Credits</div>
					<div class="font-semibold mt-1">{apiKey.credits_remaining}</div>
				</div>
				<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3">
					<div class="text-xs text-gray-500">This month</div>
					<div class="font-semibold mt-1">{apiKey.monthly_requests}</div>
				</div>
			</div>

			<div class="text-xs text-gray-500">
				Total requests: {apiKey.total_requests} • Status: {apiKey.status}
			</div>
		</div>

		{#if usage}
			<div class="rounded-xl border border-gray-100 dark:border-gray-800 p-4 space-y-2">
				<div class="text-sm font-medium">Usage & Billing Overview</div>
				<div class="grid grid-cols-2 md:grid-cols-4 gap-2 text-sm">
					<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3"><div class="text-xs text-gray-500">Monthly Requests</div><div class="font-semibold mt-1">{usage.monthly_requests}</div></div>
					<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3"><div class="text-xs text-gray-500">Pending Topups</div><div class="font-semibold mt-1">{usage.pending_topups}</div></div>
					<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3"><div class="text-xs text-gray-500">Paid Invoices</div><div class="font-semibold mt-1">{usage.paid_invoices}</div></div>
					<div class="rounded-lg border border-gray-100 dark:border-gray-800 p-3"><div class="text-xs text-gray-500">Spend</div><div class="font-semibold mt-1">${usage.total_spend_usd.toFixed(2)}</div></div>
				</div>
				<div class="text-xs text-gray-500">Avg spend / 1k requests: ${usage.avg_spend_per_1k_requests_usd.toFixed(4)} • Usage month: {usage.usage_month ?? '-'}</div>
			</div>
		{/if}

		<!-- Usage Charts -->
		{#if myUsageDaily.length > 0 || myUsageByModel.length > 0}
			<div class="grid grid-cols-1 xl:grid-cols-2 gap-3">
				<div class="rounded-xl border border-gray-100 dark:border-gray-800 p-4">
					<div class="text-sm font-medium mb-2">Daily Usage</div>
					<BarChart
						data={myUsageDaily.map((d) => ({ label: d.date, value: d.requests, secondary: d.total_cost }))}
						valueLabel="Requests"
						secondaryLabel="Cost ($)"
						barColor="#3b82f6"
						secondaryColor="#f59e0b"
						height={200}
					/>
				</div>
				<div class="rounded-xl border border-gray-100 dark:border-gray-800 p-4">
					<div class="text-sm font-medium mb-2">By Model</div>
					<BarChart
						data={myUsageByModel.map((m) => ({ label: m.model.length > 18 ? m.model.slice(0, 16) + '..' : m.model, value: m.requests, secondary: m.total_tokens }))}
						valueLabel="Requests"
						secondaryLabel="Tokens"
						barColor="#8b5cf6"
						secondaryColor="#10b981"
						height={200}
					/>
				</div>
			</div>
		{/if}

		<div class="rounded-xl border border-gray-100 dark:border-gray-800 p-4 space-y-3">
			<div class="text-sm font-medium">Top-up credits</div>
			<div class="text-xs text-gray-500">Workflow: Select plan → Submit payment request → Admin review → Credits auto/ manual approval.</div>
			<div class="grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm">
				<select class="px-2.5 py-2 rounded-lg bg-transparent border border-gray-200 dark:border-gray-700" bind:value={selectedPaymentAccountId}>
					{#if paymentAccounts.length === 0}
						<option value="">No payment accounts</option>
					{:else}
						{#each paymentAccounts as paymentAccount}
							<option value={paymentAccount.id}>{paymentAccount.provider} • {paymentAccount.account_name} • {paymentAccount.account_number}</option>
						{/each}
					{/if}
				</select>
				<input type="number" min="1" step="1" class="px-2.5 py-2 rounded-lg bg-transparent border border-gray-200 dark:border-gray-700" bind:value={topupAmount} placeholder="amount" />
				<input class="px-2.5 py-2 rounded-lg bg-transparent border border-gray-200 dark:border-gray-700" bind:value={topupCurrency} placeholder="currency" />
				<input class="px-2.5 py-2 rounded-lg bg-transparent border border-gray-200 dark:border-gray-700" bind:value={topupTxRef} placeholder="transaction reference" />
			</div>
			<textarea rows="2" class="w-full px-2.5 py-2 rounded-lg bg-transparent border border-gray-200 dark:border-gray-700 text-sm" bind:value={topupNote} placeholder="payment note"></textarea>
			<button class="px-3 py-1.5 rounded-lg bg-black text-white dark:bg-white dark:text-black text-xs" on:click={submitTopup}>Submit top-up</button>
		</div>

		<div class="grid grid-cols-1 lg:grid-cols-2 gap-3">
			<div class="rounded-xl border border-gray-100 dark:border-gray-800 overflow-x-auto">
				<div class="px-3 py-2 text-sm font-medium border-b border-gray-100 dark:border-gray-800">Top-up Requests</div>
				<table class="w-full text-xs">
					<thead class="bg-gray-50 dark:bg-gray-900/40"><tr><th class="px-3 py-2 text-left">Amount</th><th class="px-3 py-2 text-left">Ref</th><th class="px-3 py-2 text-left">Status</th></tr></thead>
					<tbody>
						{#if topups.length === 0}
							<tr><td class="px-3 py-2 text-gray-500" colspan="3">No topups</td></tr>
						{:else}
							{#each topups as topup}
								<tr class="border-t border-gray-100 dark:border-gray-800"><td class="px-3 py-2">{topup.amount} {topup.currency}</td><td class="px-3 py-2">{topup.tx_ref ?? '-'}</td><td class="px-3 py-2">{topup.status}</td></tr>
							{/each}
						{/if}
					</tbody>
				</table>
			</div>

			<div class="rounded-xl border border-gray-100 dark:border-gray-800 overflow-x-auto">
				<div class="px-3 py-2 text-sm font-medium border-b border-gray-100 dark:border-gray-800">Invoices</div>
				<table class="w-full text-xs">
					<thead class="bg-gray-50 dark:bg-gray-900/40"><tr><th class="px-3 py-2 text-left">Amount</th><th class="px-3 py-2 text-left">Credits</th><th class="px-3 py-2 text-left">Status</th><th class="px-3 py-2 text-left">Export</th></tr></thead>
					<tbody>
						{#if invoices.length === 0}
							<tr><td class="px-3 py-2 text-gray-500" colspan="4">No invoices</td></tr>
						{:else}
							{#each invoices as invoice}
								<tr class="border-t border-gray-100 dark:border-gray-800"><td class="px-3 py-2">{invoice.amount} {invoice.currency}</td><td class="px-3 py-2">{invoice.credits}</td><td class="px-3 py-2">{invoice.status}</td><td class="px-3 py-2"><button class="px-2 py-1 rounded bg-gray-100 dark:bg-gray-800" on:click={() => exportInvoicePdf(invoice.id)}>PDF</button></td></tr>
							{/each}
						{/if}
					</tbody>
				</table>
			</div>
		</div>
	{/if}
</div>
